### ISSUE TITLE
Did I probably miss something?

### ISSUE THREAD

**Issue by vinyvince** [Baldrax/Houdini_TaleSpire_Terrain_Generation_Toolset#20] opened 2022-12-18 19:09 UTC
Being doing houdini world open tools for some times and client myself ,  but i have a hard time on your set of tool and supposed demo file to understand. When i run one of the two demos file, i can not get far from just having just the terrain, certainly nothing about the biome, scattering and anything like in the video.  

Is is possible to get a more friendly example maybe ? 
Im probably not the onyl one to be confused... :)

Cheers!

I get lots of houdini error too on 19.5, python 3 : ---->

Traceback (most recent call last):
  File "Object/TaleSpire_Biome/refresh_biome", line 1, in <module>
  File "C:\Users/vincent/Documents/houdini19.5/Houdini_TaleSpire_Terrain_Generation_Toolset-master/scripts/python\htg\nodes\OBJ_TaleSpire_Biome.py", line 11, in refresh_biome
    cook_node.cook(force=True)
  File "C:\PROGRA~1/SIDEEF~1/Houdini 19.5.368/houdini/python3.9libs\hou.py", line 16926, in cook
    return _hou.Node_cook(self, *args, **kwargs)
hou.Operation failed: The attempted operation failed.
Error while cooking.

**Comment by Baldrax** [comment] 2022-12-20 22:25
I am working on tutorials but I do this in my free time which I do not have a lot of these days.
I'm not sure why you haven't been able to see the biome networks, the example_Forest_Gully.hipnc file should contain a fully working terrain.

You have to follow the initial steps to be able to see the terrain.
![image](https://user-images.githubusercontent.com/100365731/208776456-7cbf8537-d7b4-41c9-839d-5508f2dd9b52.png)

I do notice some load warnings when I launch in Houdini 19.5 but they have not affected functionality at all.
The toolset is developed using 19.0 for now, since it helps with backwards compatibility.
Do you know what version of the toolset you are using?
The latest build is [v0.18.0-alpha](https://github.com/Baldrax/Houdini_TaleSpire_Terrain_Generation_Toolset/releases/tag/v0.18.0-alpha)

**Comment by vinyvince** [comment] 2022-12-23 13:42
Thanks you i will give another try this weekend, looking forward ! :)

**Comment by Baldrax** [comment] 2022-12-28 04:46
Let me know if it worked.
I'm curious what causes that python error as I wasn't able to duplicate it.  I thought maybe it might happen if TaleSpire wasn't installed, but even that didn't prompt that error.

⚠This does require TaleSpire to work.

**Comment by Baldrax** [comment] 2023-01-19 20:41
I'm going to mark this closed in a few more days if there isn't any further information.

**Comment by Baldrax** [comment] 2023-01-26 11:40
Closing this as I cannot reproduce the issue. I suspect it might be because TaleSpire is not install and/or a non standard python or Houdini installation on the system.

**Closed as not planned by Baldrax** 2023-01-26 11:40 UTC
Labels: question
